config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :weights, only: [:new, :create, :edit, :update, :destroy]

  get 'static_pages/index'

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'

  root 'static_pages#index'
  get '*anything' => 'errors#routing_error'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :weights, dependent: :destroy

  before_save { email.downcase! }
  before_create :create_remember_token

  validates :name,
    presence: true,
    length: { maximum: 50 }
  validates :email,
    presence: true,
    email_format: { message: 'email format is invalid' },
    uniqueness: true
  validates :password,
    presence: true,
    length: { minimum: 6 }
  validates :password_confirmation,
    presence: true
  
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :user

  validates :date,
    presence: true
  validates :weight,
    presence: true,
    numericality: { greater_than: 0 }
  validates :user_id,
    presence: true,
    uniqueness: { scope: :date }

  def self.current_weight(user)
    where(user_id: user.id).order('date DESC').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ErrorHandlers if Rails.env.production?
  include SessionsHelper
end

app/controllers/concerns/error_handlers.rb
module ErrorHandlers
  extend ActiveSupport::Concern

  included do
    rescue_from Exception, with: :rescue500
    rescue_from ActionController::ParameterMissing, with: :rescue400
    rescue_from ActionController::RoutingError, with: :rescue404
    rescue_from ActiveRecord::RecordNotFound, with: :rescue404
  end

  private

    def rescue400(e)
      @exception = e
      render 'errors/bad_request', status: 400
    end

    def rescue404(e)
      @exception = e
      render 'errors/not_found', status: 404
    end

    def rescue500(e)
      @exception = e
      render 'errors/internal_server_error', status: 500
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def routing_error
    raise ActionController::RoutingError,
      "No route matches #{request.path.inspect}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'メールアドレスとパスワードの組み合わせが正しくありません'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 15).order('name ASC')
  end

  def show
    @user = User.find(params[:id])
    @weights = @user.weights.paginate(page: params[:page], per_page: 14).order('date DESC')

    current_weight = Weight.current_weight(@user)
    if current_weight.nil?
      @current_weight = '-'
      @current_date = '----年--月--日'
    else
      @current_weight = current_weight.weight
      @current_date = current_weight.date.strftime('%Y年%m月%d日')
    end

    @graph_data = @weights.order('date ASC').group(:date).sum(:weight)
    @min_value_in_chart = @weights.select(:weight).order('weight DESC').first
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user, notice: 'ユーザー情報を登録しました'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報を更新しました'
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: 'ユーザー情報を削除しました'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :target_weight, :password,
                                  :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: 'サインインしてください'
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController

  def new
    @weight = Weight.new(user: current_user)
  end

  def create
    @weight = Weight.new(weight_params)
    @weight.user = current_user
    if @weight.save
      redirect_to user_path(@weight.user), notice: '体重を登録しました'
    else
      render 'new'
    end
  end

  def edit
    @weight = Weight.find(params[:id])
  end

  def update
    @weight = Weight.find(params[:id])
    if @weight.update(weight_params)
      redirect_to user_path(@weight.user), notice: '体重を変更しました'
    else
      render 'edit'
    end
  end

  def destroy
    @weight = Weight.find(params[:id])
    @weight.destroy
    redirect_to user_path(@weight.user), notice: '体重を削除しました'
  end

  private

    def weight_params
      params.require(:weight).permit(:date, :weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = '体重管理'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <p>
    Copyright &copy;
    <%= link_to 'prime factor', 'http://www.succi.jp/blog/', { target: '_balnk'} %>,
    2014 All Rights Reserved.
  </p>
  <%= debug(params) if Rails.env.development? %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '体重管理', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', about_path %></li>
<li><%= link_to 'Contact', contact_path %></li>
<% if signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li class="dropdown">
    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
      Account <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Profile', current_user %></li>
      <li><%= link_to 'Settings', edit_user_path(current_user) %>
      <li class="divider"></li>
      <li>
        <%= link_to 'Sign out', signout_path, method: "delete" %>
      </li>
    </ul>
  </li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Taiju Kanri" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <link href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/cosmo/bootstrap.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

    <footer class="site-footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, 'About' %>

<div class="container">
  <div class="page-header">
    <h2>このサイトについて</h2>
  </div>

  <h3>体重管理</h3>

  <p>
    「体重管理」は、体重を記録するためのウェブアプリケーションです。日々の体重を記録すると、体重の推移をグラフに表示します。
  </p>

  <p>
    ログインすると他のユーザーの情報を閲覧することができます。
  </p>
</div>

app/views/static_pages/contact.html.erb
<% provide :title, 'Contact' %>

<div class="container">
  <div class="page-header">
    <h2>お問い合わせ</h2>
  </div>

  <h3>連絡先</h3>

  <p>
    お問い合わせは、下記Twitterアカウント宛てにメッセージをいただくか、ブログのコンタクトフォームからご連絡をいただきますようお願いします。
  </p>

  <dl>
    <dt><%= fa_icon "twitter", text: "Twitter" %></dt>
    <dd><%= link_to '@succi0303', 'https://twitter.com/succi0303', { target: '_blank' } %></dd>
    <dt><%= fa_icon "rss-square", text: "Blog" %></dt>
    <dd><%= link_to 'prime factor', 'http://www.succi.jp/blog/', { target: '_blank' } %></dd>
  </dl>

  <h3>ソースコード</h3>

  <p>
    本ウェブサイトのソースコードはGithubで公開しています。ご興味を持っていただいた方は下記のGithubリポジトリを参照ください。
  </p>

  <dl>
    <dt><%= fa_icon "github", text: "Github" %></dt>
    <dd><%= link_to 'succi0303/taiju_kanri',
      'https://github.com/succi0303/taiju_kanri',
      { target: '_blank' } %></dd>
  </dl>
</div>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>体重管理</h1>
    <p>日々の体重を登録して推移をグラフで確認します。</p>
    <p><%= link_to 'ユーザー登録 »', new_user_path,
      class: 'btn btn-primary btn-lg' %></p>
  </div>

  <div class="notes">
    <p>作成者自身のプログラム学習を目的に作成しているアプリケーションです。<br>
      内容は随時変更する可能性が有りますのでご注意ください。</p>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :name, label: '名前',
    placeholder: '名前を入力してください',
    autofocus: true %>
  <%= f.input :email, label: 'メールアドレス',
    placeholder: 'メールアドレスを入力してください'%>
  <%= f.input :target_weight, label: '目標体重(kg)',
    placeholder: '目標体重を入力してください' %>
  <%= f.input :password, label: 'パスワード',
    placeholder: 'パスワードを入力してください' %>
  <%= f.input :password_confirmation, label: 'パスワード確認',
    placeholder: 'パスワードをもう一度入力してください' %>
  <%= f.button :submit, value: '登録する', class: 'btn-primary',
    data: { disable_with: '登録中...' } %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'ユーザー更新') %>

<div class="container">

  <div class="page-header">
    <h2>ユーザー更新</h2>
  </div>

  <p>
    <%= render 'form' %>
  </p>

  <div class="alert alert-warning">
    <p>
      <%= fa_icon('exclamation-triangle') %>
      <strong>ユーザー情報の削除</strong><br />
      ユーザー情報とユーザーに関連するすべての情報を削除します。
      この操作は取り消しできませんので注意してください。<br />
      <%=
        link_to 'ユーザー情報の削除', user_path(current_user),
          method: :delete,
          data: { confirm: '削除してもよろしいですか？' },
          class: 'btn btn-danger btn-sm'
      %>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー情報一覧') %>

<div class="container">

  <div class="page-header">
    <h2>ユーザー情報一覧</h2>
  </div>

  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>

  <table class="table table-bordered">
    <tr>
      <th>名前</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
      </tr>
    <% end %>
  </table>

  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'ユーザー登録') %>

<div class="container">
  <div class="page-header">
    <h2>ユーザー登録</h2>
  </div>

  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="container" id="pagetop">

  <div class="page-header">
    <h2><%= @user.name %></h2>
  </div>

  <div class="panel panel-default">
    <div class="panel-body">
      <dl>
        <dt>目標体重</dt>
        <dd><%= @user.target_weight %> kg</dd>
        <dt>現在の体重 ( <%= @current_date %>現在 )</dt>
        <dd><%= @current_weight %> kg</dd>
      </dl>
    </div>
  </div>

  <% if @user == current_user %>
    <p>
      <%= link_to fa_icon('pencil-square-o', text: '体重を登録する'),
        new_weight_path,
        class: 'btn btn-primary', data: { no_turbolink: true } %>
    </p>
  <% else %>
    <p>
      <%= link_to fa_icon('pencil-square-o', text: '体重を登録する'),
        new_weight_path,
        class: 'btn btn-primary', data: { no_turbolink: true }, disabled: true %>
    </p>
  <% end %>

  <div class="weight-graph">
    <%= line_chart @graph_data, min: @min_value_in_chart %>
  </div>

  <%= will_paginate @weights, renderer: BootstrapPagination::Rails %>

  <table class="table table-bordered table-striped">
    <tr>
      <th>年月日</th>
      <th>体重(kg)</th>
      <th>修正 / 削除</th>
    </tr>

    <% if @user.weights.any? %>
      <%= render @weights %>
    <% end %>
  </table>

  <%= link_to  '先頭へ戻る', '#pagetop',
    class: 'btn btn-warning',
    id: 'return-to-top'
  %>

</div>

app/views/weights/_form.html.erb
<%= simple_form_for(@weight) do |f| %>
  <%= f.input :date, as: :string, label: '年月日(yyyy-mm-dd)',
    input_html: { class: 'datepicker' } %>
  <%= f.input :weight, label: '体重' %>
  <%= f.button :submit, value: '登録する', class: 'btn-primary',
    data: { disable_with: '登録中...' } %>
<% end %>

app/views/weights/_weight.html.erb
<tr>
  <td><%= weight.date.strftime('%Y年%m月%d日') %></td>
  <td><%= weight.weight %> kg</td>

  <% if @user == current_user %>
    <td>
      <%= link_to fa_icon('check-circle', text: '修正'),
        edit_weight_path(weight),
        class: 'btn btn-warning btn-xs', data: { no_turbolink: true } %>
      <%= link_to fa_icon('times-circle', text: '削除'),
        weight_path(weight),
        method: :delete,
        data: { confirm: '削除してよろしいですか？' },
        class: 'btn btn-danger btn-xs' %>
    </td>
  <% else %>
    <td>
      <%= link_to fa_icon('check-circle', text: '修正'),
        edit_weight_path(weight),
        class: 'btn btn-warning btn-xs', data: { no_turbolink: true }, disabled: true %>
      <%= link_to fa_icon('times-circle', text: '削除'),
        weight_path(weight),
        method: :delete,
        data: { confirm: '削除してよろしいですか？' },
        class: 'btn btn-danger btn-xs', disabled: true %>
    </td>
  <% end %>

</tr>

app/views/weights/edit.html.erb
<% provide(:title, '体重を変更する') %>

<div class="container">
  <div class="page-header">
    <h2>体重を変更する</h2>
  </div>

  <p>
    <%= link_to fa_icon('undo', text: 'プロフィールに戻る'),
      user_path(current_user), class: 'btn btn-default' %>
  </p>

  <%= render 'form' %>
</div>

app/views/weights/new.html.erb
<% provide(:title, '体重を登録する') %>

<div class="container">
  <div class="page-header">
    <h2>体重を登録する</h2>
  </div>

  <p>
    <%= link_to fa_icon('undo', text: 'プロフィールに戻る'),
      user_path(current_user),
      class: 'btn btn-default' %>
  </p>

  <%= render 'form' %>
</div>